# --- ПАРАМЕТРИ ZENSTAT ---

# Локація для погоди
CITY="Hostomel"

# Шлях до логів CoreTemp (Windows)
CORE_TEMP_PATH="/mnt/c/ProgramData/chocolatey/lib/coretemp/tools"

# Тимчасові файли
WEATHER_CACHE="/tmp/zenstat_weather"

# Кольорова схема (ANSI коди)
COLOR_CYAN="\033[0;36m"
COLOR_GREEN="\033[0;32m"
COLOR_YELLOW="\033[0;33m"
COLOR_RED="\033[1;31m"
COLOR_PURPLE="\033[1;35m"
COLOR_RESET="\033[0m"
